[theme]
theme = "gruvbox-dark"
[icons]
icons = "awesome4"

[[block]]
block = "custom"
command = "echo '\uf120 '"
interval = "once"
[[block.click]]
button = "left"
cmd = 'swaymsg exec alacritty'

[[block]]
block = "net"
# device = '^enp8s0'
format = " $icon $device {$signal_strength $ssid $frequency|}"
[[block.click]]
button = "left"
cmd = "swaymsg exec 'alacritty -t NetworkManager --class twl_nm -e nmtui'"


[[block]]
block = "memory"
format = "$icon $mem_used_percents.eng(w:2, pad_with:0)"

[[block]]
block = "cpu"
interval = 2
format = "$icon $utilization.eng(w:2, pad_with:0)"

[[block]]
block = "time"
interval = 2
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R', l:en_US) "
short = "$icon $timestamp.datetime(f:%R) "

[[block]]
block = "battery"
missing_format = ""

[[block]]
block = "sound"
